server:
  port: 9001
spring:
  application:
    name: producer
  zipkin:
    base-url: http://localhost:9000
  sleuth:
    sampler:
      percentage: 0.2
      uriSample:
        - uriRegex: "/test/"
          uriPercentage: 0.9
        - uriRegex: "/user/"
          uriPercentage: 0.5



eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/